using Azure.Messaging.ServiceBus;
using Azure.Search.Documents;
using Azure.Search.Documents.Models;
using EnterpriseDocumentIntelligence.BuildingBlocks.Infrastructure;
using EnterpriseDocumentIntelligence.BuildingBlocks.Messaging;
using System.Text.Json;
public sealed class ServiceBusClientFactory(IConfiguration c){private readonly ServiceBusClient client=!string.IsNullOrWhiteSpace(c["ServiceBus:ConnectionString"])?new(c["ServiceBus:ConnectionString"]!):new(c["ServiceBus:FullyQualifiedNamespace"]!,new Azure.Identity.DefaultAzureCredential());public ServiceBusProcessor Create(string t,string s)=>client.CreateProcessor(t,s,new ServiceBusProcessorOptions{MaxConcurrentCalls=8,PrefetchCount=50,AutoCompleteMessages=false});}
public sealed class Worker(ServiceBusClientFactory factory,IndexProvisioner provisioner,SearchClient index,IMessagePublisher publisher,ILogger<Worker> log,IndexDocumentValidator validator):BackgroundService
{
 protected override async Task ExecuteAsync(CancellationToken ct){await provisioner.EnsureAsync(ct);var p=factory.Create(Topics.EmbeddingEvents,"indexing-sub");var acl=factory.Create(Topics.DocumentEvents,"indexing-acl-sub");p.ProcessMessageAsync+=Handle;p.ProcessErrorAsync+=Error;acl.ProcessMessageAsync+=HandleAcl;acl.ProcessErrorAsync+=Error;await p.StartProcessingAsync(ct);await acl.StartProcessingAsync(ct);try{await Task.Delay(Timeout.Infinite,ct);}catch(OperationCanceledException) when(ct.IsCancellationRequested){}finally{await p.StopProcessingAsync();await acl.StopProcessingAsync();await p.DisposeAsync();await acl.DisposeAsync();}}
 private async Task Handle(ProcessMessageEventArgs a){try{var m=JsonSerializer.Deserialize<EmbeddingsCreated>(a.Message.Body.ToString(),new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new InvalidDataException("Invalid embeddings event.");var batch=new IndexDocumentsBatch<SearchDocument>();foreach(var c in m.Chunks){validator.Validate(m.TenantId,m.DocumentId,c.ChunkId,c.Number,c.Text,c.AllowedPrincipalIds??[],c.Embedding);var principals=(c.AllowedPrincipalIds??[]).Select(x=>x.ToString()).ToArray();batch.Actions.Add(IndexDocumentsAction.Upload(new SearchDocument{{"id",c.ChunkId.ToString()},{"TenantId",m.TenantId.ToString()},{"DocumentId",m.DocumentId.ToString()},{"ChunkId",c.ChunkId.ToString()},{"ChunkNumber",c.Number},{"Text",c.Text},{"Citation",$"document:{m.DocumentId}/version:{m.VersionId}/chunk:{c.Number}"},{"ContentVector",c.Embedding},{"AllowedPrincipalIds",principals}}));}await index.IndexDocumentsAsync(batch,cancellationToken:a.CancellationToken);await publisher.PublishAsync(Topics.IndexingEvents,new IndexingCompleted(Guid.NewGuid(),m.TenantId,m.DocumentId,m.VersionId,m.Chunks.Count,DateTimeOffset.UtcNow,m.CorrelationId),m.CorrelationId,a.CancellationToken);await a.CompleteMessageAsync(a.Message);}catch(Exception ex){log.LogError(ex,"Indexing failed");if(a.Message.DeliveryCount>=5)await a.DeadLetterMessageAsync(a.Message,"max-delivery",ex.Message);else await a.AbandonMessageAsync(a.Message);}}
 private async Task HandleAcl(ProcessMessageEventArgs a){try{var m=JsonSerializer.Deserialize<DocumentAclChanged>(a.Message.Body.ToString(),new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new InvalidDataException("Invalid ACL event.");var filter=$"TenantId eq '{m.TenantId}' and DocumentId eq '{m.DocumentId}'";var response=await index.SearchAsync<SearchDocument>("*",new SearchOptions{Filter=filter,Size=1000,Select={"id"}},a.CancellationToken);var ids=new List<string>();await foreach(var r in response.Value.GetResultsAsync())if(r.Document.GetString("id") is{Length:>0} id)ids.Add(id);if(ids.Count>0){var batch=new IndexDocumentsBatch<SearchDocument>();var principals=m.AllowedPrincipalIds.Select(x=>x.ToString()).ToArray();foreach(var id in ids)batch.Actions.Add(IndexDocumentsAction.Merge(new SearchDocument{{"id",id},{"AllowedPrincipalIds",principals}}));await index.IndexDocumentsAsync(batch,cancellationToken:a.CancellationToken);}await a.CompleteMessageAsync(a.Message);}catch(Exception ex){log.LogError(ex,"ACL indexing failed");if(a.Message.DeliveryCount>=5)await a.DeadLetterMessageAsync(a.Message,"max-delivery",ex.Message);else await a.AbandonMessageAsync(a.Message);}}
 private Task Error(ProcessErrorEventArgs e){log.LogError(e.Exception,"Indexing Service Bus error Entity={Entity}",e.EntityPath);return Task.CompletedTask;}
}