<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../SearchService.Domain/SearchService.Domain.csproj"/><ProjectReference Include="../../BuildingBlocks/BuildingBlocks.csproj"/></ItemGroup></Project>