<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../../BuildingBlocks/BuildingBlocks.csproj"/>  <ProjectReference Include="../EmbeddingService.Application/EmbeddingService.Application.csproj" />
    <ProjectReference Include="../EmbeddingService.Infrastructure/EmbeddingService.Infrastructure.csproj" />
</ItemGroup><ItemGroup><PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/></ItemGroup></Project>