<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SearchService.Application/SearchService.Application.csproj" />
    <PackageReference Include="Azure.Search.Documents" Version="11.7.0" />
  </ItemGroup>
</Project>