<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../../BuildingBlocks/BuildingBlocks.csproj"/><ProjectReference Include="../IngestionService.Application/IngestionService.Application.csproj"/><ProjectReference Include="../IngestionService.Infrastructure/IngestionService.Infrastructure.csproj"/></ItemGroup><ItemGroup><PackageReference Include="Azure.Storage.Blobs" Version="12.25.1"/><PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/></ItemGroup></Project>